### ISSUE TITLE
 throw new Error('Emoji favicon: emoji-images package not found.');

### ISSUE THREAD

**Issue by mikeumus** [rumkin/emoji-favicon#2]
Thanks for the quick fix. Now am running into this on the build script it looks like:

``` console
mikeumus@dev-instance-2:~/ngRockPaperScissors$ npm start

> rps-front-end@0.0.0 start /home/mikeumus/ngRockPaperScissors
> PORT=8081 node ./bin/www

/home/mikeumus/ngRockPaperScissors/node_modules/emoji-favicon/build/emoji-favicon.js:8
    throw new Error('Emoji favicon: emoji-images package not found.');
    ^

Error: Emoji favicon: emoji-images package not found.
    at Object.<anonymous> (/home/mikeumus/ngRockPaperScissors/node_modules/emoji-favicon/build/emoji-favicon.js:8:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/mikeumus/ngRockPaperScissors/app.js:7:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by rumkin** [comment]
Cannot reproduce. What version of node/npm do you use? What does `ls node_modules/emoji-favicon/node_modules` return?

**Comment by rumkin** [comment]
Try v0.3.0
